/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OORestaurants;
import java.awt.Component;
import javax.swing.JTextField;
import java.awt.TextField;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author krati
 */
public class OO_Restaurant extends javax.swing.JFrame {

    /**
     * Creates new form OO_Restaurant
     */
    public OO_Restaurant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        jTxtTax = new javax.swing.JTextField();
        jTxtTotalAmount = new javax.swing.JTextField();
        jTxtSubTotal = new javax.swing.JTextField();
        jbTax = new javax.swing.JLabel();
        jbTotal = new javax.swing.JLabel();
        jbSubTotal = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtReceipt = new javax.swing.JTextArea();
        jPanel36 = new javax.swing.JPanel();
        jBtnTotal = new javax.swing.JButton();
        jBtnReceipt = new javax.swing.JButton();
        jBtnReset = new javax.swing.JButton();
        jBtnExit = new javax.swing.JButton();
        jPanel31 = new javax.swing.JPanel();
        jbTax4 = new javax.swing.JLabel();
        jbVegCheeseSandwich = new javax.swing.JLabel();
        jbFarmHousePizzza = new javax.swing.JLabel();
        jbSpecialBurger = new javax.swing.JLabel();
        jbHakkaNoodles = new javax.swing.JLabel();
        jbTandooriMomos = new javax.swing.JLabel();
        jTMomos = new javax.swing.JTextField();
        jTNoodles = new javax.swing.JTextField();
        jTBurger = new javax.swing.JTextField();
        jTPIzza = new javax.swing.JTextField();
        jTSandwich = new javax.swing.JTextField();
        jPanel33 = new javax.swing.JPanel();
        jbCostOfMeal = new javax.swing.JLabel();
        jbCostOfDrinks = new javax.swing.JLabel();
        jbTotalCostOfFood = new javax.swing.JLabel();
        jTxtMealsCost = new javax.swing.JTextField();
        jTxtDrinksCost = new javax.swing.JTextField();
        jTxtTotalCost = new javax.swing.JTextField();
        jPanel32 = new javax.swing.JPanel();
        jTIceTea = new javax.swing.JTextField();
        jTKitKatShake = new javax.swing.JTextField();
        jTOreoShake = new javax.swing.JTextField();
        jbTax3 = new javax.swing.JLabel();
        jTColdCoffee = new javax.swing.JTextField();
        jTChocMilkshake = new javax.swing.JTextField();
        jbChocolateMilkshake = new javax.swing.JLabel();
        jbColdCoffee = new javax.swing.JLabel();
        jbIceTea = new javax.swing.JLabel();
        jbKitKatShake = new javax.swing.JLabel();
        jbOreoShake = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 0, 0));
        setForeground(java.awt.Color.black);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 12));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Castellar", 3, 45)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Restaurant  Management  System");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 204), 8, true));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\krati\\Downloads\\restaurant-1724294_1280.png")); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153), 8));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\krati\\Downloads\\restaurant-1724294_1280.png")); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 153), 8));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1095, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1450, 170));

        jPanel34.setBackground(new java.awt.Color(255, 153, 153));
        jPanel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 12));
        jPanel34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTxtTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxtTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTaxActionPerformed(evt);
            }
        });
        jPanel34.add(jTxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 23, 160, -1));

        jTxtTotalAmount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxtTotalAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTotalAmountActionPerformed(evt);
            }
        });
        jPanel34.add(jTxtTotalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 99, 160, -1));

        jTxtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtSubTotalActionPerformed(evt);
            }
        });
        jPanel34.add(jTxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 60, 160, -1));

        jbTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbTax.setText("TAX");
        jPanel34.add(jbTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 380, 30));

        jbTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbTotal.setText("TOTAL AMOUNT");
        jPanel34.add(jbTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 380, 30));

        jbSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbSubTotal.setText("SUB TOTAL");
        jPanel34.add(jbSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 350, 30));

        getContentPane().add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, 530, 150));

        jPanel35.setBackground(new java.awt.Color(255, 153, 153));
        jPanel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 12));
        jPanel35.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTxtReceipt.setColumns(20);
        jTxtReceipt.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTxtReceipt.setRows(5);
        jScrollPane1.setViewportView(jTxtReceipt);

        jPanel35.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 33, 320, 480));

        getContentPane().add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 190, 360, 540));

        jPanel36.setBackground(new java.awt.Color(255, 153, 153));
        jPanel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 12));
        jPanel36.setLayout(null);

        jBtnTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnTotal.setText("TOTAL");
        jBtnTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTotalActionPerformed(evt);
            }
        });
        jPanel36.add(jBtnTotal);
        jBtnTotal.setBounds(51, 17, 200, 29);

        jBtnReceipt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnReceipt.setText("RECEIPT");
        jBtnReceipt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnReceiptActionPerformed(evt);
            }
        });
        jPanel36.add(jBtnReceipt);
        jBtnReceipt.setBounds(294, 17, 210, 29);

        jBtnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnReset.setText("RESET");
        jBtnReset.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnResetActionPerformed(evt);
            }
        });
        jPanel36.add(jBtnReset);
        jBtnReset.setBounds(571, 17, 200, 29);

        jBtnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jBtnExit.setText("EXIT");
        jBtnExit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExitActionPerformed(evt);
            }
        });
        jPanel36.add(jBtnExit);
        jBtnExit.setBounds(819, 17, 200, 29);

        getContentPane().add(jPanel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, 1080, 60));

        jPanel31.setBackground(new java.awt.Color(255, 153, 153));
        jPanel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 12));
        jPanel31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbTax4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbTax4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbTax4.setText("MEALS");
        jPanel31.add(jbTax4, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 12, 104, 44));

        jbVegCheeseSandwich.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbVegCheeseSandwich.setText("VEGETABLES CHEESE SANDWICH");
        jPanel31.add(jbVegCheeseSandwich, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 350, 30));

        jbFarmHousePizzza.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbFarmHousePizzza.setText("FARM-HOUSE PIZZA");
        jPanel31.add(jbFarmHousePizzza, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 350, 30));

        jbSpecialBurger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbSpecialBurger.setText("SPECIAL BURGER");
        jPanel31.add(jbSpecialBurger, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 350, 30));

        jbHakkaNoodles.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbHakkaNoodles.setText("HAKKA NOODLES");
        jPanel31.add(jbHakkaNoodles, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 350, 30));

        jbTandooriMomos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbTandooriMomos.setText("TANDOORI MOMOS");
        jPanel31.add(jbTandooriMomos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 350, 30));

        jTMomos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTMomos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTMomosActionPerformed(evt);
            }
        });
        jPanel31.add(jTMomos, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 94, -1));

        jTNoodles.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTNoodles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNoodlesActionPerformed(evt);
            }
        });
        jPanel31.add(jTNoodles, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 94, -1));

        jTBurger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTBurgerActionPerformed(evt);
            }
        });
        jPanel31.add(jTBurger, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 94, -1));

        jTPIzza.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTPIzza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPIzzaActionPerformed(evt);
            }
        });
        jPanel31.add(jTPIzza, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 94, -1));

        jTSandwich.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTSandwich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTSandwichActionPerformed(evt);
            }
        });
        jPanel31.add(jTSandwich, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 94, -1));

        getContentPane().add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 540, 310));

        jPanel33.setBackground(new java.awt.Color(255, 153, 153));
        jPanel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 12));
        jPanel33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbCostOfMeal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbCostOfMeal.setText("COST OF MEAL");
        jPanel33.add(jbCostOfMeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 26, 290, -1));

        jbCostOfDrinks.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbCostOfDrinks.setText("COST OF DRINKS");
        jPanel33.add(jbCostOfDrinks, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 63, 300, -1));

        jbTotalCostOfFood.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbTotalCostOfFood.setText("TOTAL COST OF FOOD");
        jPanel33.add(jbTotalCostOfFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 102, 290, -1));

        jTxtMealsCost.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxtMealsCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtMealsCostActionPerformed(evt);
            }
        });
        jPanel33.add(jTxtMealsCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 20, 160, -1));

        jTxtDrinksCost.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxtDrinksCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtDrinksCostActionPerformed(evt);
            }
        });
        jPanel33.add(jTxtDrinksCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 60, 160, -1));

        jTxtTotalCost.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTxtTotalCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTotalCostActionPerformed(evt);
            }
        });
        jPanel33.add(jTxtTotalCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 99, 160, -1));

        getContentPane().add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 540, 150));

        jPanel32.setBackground(new java.awt.Color(255, 153, 153));
        jPanel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 204), 12));
        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTIceTea.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTIceTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTIceTeaActionPerformed(evt);
            }
        });
        jPanel32.add(jTIceTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 94, -1));

        jTKitKatShake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTKitKatShake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTKitKatShakeActionPerformed(evt);
            }
        });
        jPanel32.add(jTKitKatShake, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 94, -1));

        jTOreoShake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTOreoShake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTOreoShakeActionPerformed(evt);
            }
        });
        jPanel32.add(jTOreoShake, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 94, -1));

        jbTax3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbTax3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbTax3.setText("DRINKS");
        jPanel32.add(jbTax3, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 12, 104, 44));

        jTColdCoffee.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTColdCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTColdCoffeeActionPerformed(evt);
            }
        });
        jPanel32.add(jTColdCoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 94, -1));

        jTChocMilkshake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTChocMilkshake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTChocMilkshakeActionPerformed(evt);
            }
        });
        jPanel32.add(jTChocMilkshake, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 94, -1));

        jbChocolateMilkshake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbChocolateMilkshake.setText("CHOCOLATE MILKSHAKE");
        jPanel32.add(jbChocolateMilkshake, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 350, 30));

        jbColdCoffee.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbColdCoffee.setText("COLD COFFEE");
        jPanel32.add(jbColdCoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 350, 30));

        jbIceTea.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbIceTea.setText("ICE TEA");
        jPanel32.add(jbIceTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 350, 30));

        jbKitKatShake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbKitKatShake.setText("KIT-KAT SHAKE");
        jPanel32.add(jbKitKatShake, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 350, 30));

        jbOreoShake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbOreoShake.setText("OREO SHAKE");
        jPanel32.add(jbOreoShake, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 350, 30));

        getContentPane().add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 530, 310));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTotalActionPerformed
        // TODO add your handling code here:
        SubClass_Child itemCost = new SubClass_Child();
        
        double itax, itotal , isubtotal;
        
        itemCost.chocolateMilkshake = itemCost.pchocolateMilkshake * Double.parseDouble(jTChocMilkshake.getText());
        itemCost.iceTea = itemCost.piceTea * Double.parseDouble(jTIceTea.getText());
        itemCost.kitkatShake = itemCost.pkitkatShake * Double.parseDouble(jTKitKatShake.getText());
        itemCost.oreoShake = itemCost.poreoShake * Double.parseDouble(jTOreoShake.getText());
        itemCost.coldCoffee = itemCost.pcoldCoffee * Double.parseDouble(jTColdCoffee.getText());
         
        itemCost.farmhousePizza = itemCost.pfarmhousePizza * Double.parseDouble(jTPIzza.getText());
        itemCost.tandooriMomos = itemCost.ptandooriMomos * Double.parseDouble(jTMomos.getText());
        itemCost.hakkaNoodles = itemCost.phakkaNoodles * Double.parseDouble(jTNoodles.getText());
        itemCost.vegChesseSandwich = itemCost.pvegChesseSandwich * Double.parseDouble(jTSandwich.getText());
        itemCost.specialBurger = itemCost.pspecialBurger * Double.parseDouble(jTBurger.getText());
        
        isubtotal = itemCost.GetAmount();
        itax = itemCost.cFIndTax(isubtotal);
        itotal = isubtotal + itax;
        
        String Tax = String.format("₹ %.2f", itax);
        jTxtTax.setText(Tax);
        
        String SubTotal = String.format("₹ %.2f", isubtotal);
        jTxtSubTotal.setText(SubTotal);
        
        String Total = String.format("₹ %.2f", itotal);
        jTxtTotalAmount.setText(Total);
        
        String Meal = String.format("₹ %.2f", itemCost.Meals);
        jTxtMealsCost.setText(Meal);
        
        String Drink  = String.format("₹ %.2f", itemCost.Drinks);
        jTxtDrinksCost.setText(Drink);
        
        String TotalCost  = String.format("₹ %.2f", itemCost.TotalOfMD);
        jTxtTotalCost.setText(TotalCost);
        
        
        
    }//GEN-LAST:event_jBtnTotalActionPerformed

    private void jBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExitActionPerformed
        // TODO add your handling code here:
        SubClass_Child iExit = new SubClass_Child();
        
        iExit.iExitSystem();
    }//GEN-LAST:event_jBtnExitActionPerformed

    private void jTxtTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTaxActionPerformed

    private void jTxtTotalAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTotalAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTotalAmountActionPerformed

    private void jTxtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtSubTotalActionPerformed

    private void jTIceTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTIceTeaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTIceTeaActionPerformed

    private void jTKitKatShakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTKitKatShakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTKitKatShakeActionPerformed

    private void jTOreoShakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTOreoShakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTOreoShakeActionPerformed

    private void jTColdCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTColdCoffeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTColdCoffeeActionPerformed

    private void jTChocMilkshakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTChocMilkshakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTChocMilkshakeActionPerformed

    private void jTMomosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTMomosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTMomosActionPerformed

    private void jTNoodlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNoodlesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNoodlesActionPerformed

    private void jTBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTBurgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTBurgerActionPerformed

    private void jTPIzzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPIzzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPIzzaActionPerformed

    private void jTSandwichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTSandwichActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTSandwichActionPerformed

    private void jTxtMealsCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtMealsCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtMealsCostActionPerformed

    private void jTxtDrinksCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDrinksCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtDrinksCostActionPerformed

    private void jTxtTotalCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTotalCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTotalCostActionPerformed

    private void jBtnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReceiptActionPerformed
        
        //======================================
        int refs = 1325 + (int)(Math.random()*4238);
        //========================================
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat Tdate = new SimpleDateFormat("dd-MM-yy");
        Tdate.format(timer.getTime());
        
        
                       jTxtReceipt.append("   RESTAURANT MANAGEMENT SYSTEMS\n" +
                               " \t  Reference: "+refs+
                               "\n ==================================\n"+
                               "  Meals:\t\t" + jTxtMealsCost.getText() + "\n\n"+
                               "  Drinks:\t\t" + jTxtDrinksCost.getText() + "\n\n"+
                               "  Cost of Items:\t" +jTxtTotalCost.getText()+"\n\n"+
                                 " ==================================" + "\n\n"+
                               "  Tax:\t\t\t" + jTxtTax.getText()+"\n\n" + 
                               "  Subtotal:\t\t" + jTxtSubTotal.getText()+"\n\n"+
                               "  Total:\t\t" + jTxtTotalAmount.getText()+"\n"+
                                 " =================================="+
                               "\n Date: " + Tdate.format(timer.getTime()) +
                               "    Time: " + tTime.format(timer.getTime()) + 
                               "\n\n    Thank You for visiting us!!!");
    }//GEN-LAST:event_jBtnReceiptActionPerformed

    private void jBtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnResetActionPerformed
        // TODO add your handling code here:
        JTextField cleartext = null;
        //panel1
        for(Component c: jPanel31.getComponents())
        {
            if(c.getClass().toString().contains("javax.swing.JTextField"))
            {
                cleartext = (JTextField)c;
                cleartext.setText("0");
            }
        }
        //panel2
        for(Component c: jPanel32.getComponents())
        {
            if(c.getClass().toString().contains("javax.swing.JTextField"))
            {
                cleartext = (JTextField)c;
                cleartext.setText("0");
            }
        }
        //panel3
        for(Component c: jPanel33.getComponents())
        {
            if(c.getClass().toString().contains("javax.swing.JTextField"))
            {
                cleartext = (JTextField)c;
                cleartext.setText("");
            }
        }
        //panel4
        for(Component c: jPanel34.getComponents())
        {
            if(c.getClass().toString().contains("javax.swing.JTextField"))
            {
                cleartext = (JTextField)c;
                cleartext.setText("");
            }
        }
        jTxtReceipt.setText(null);
    }//GEN-LAST:event_jBtnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, IllegalAccessException, InstantiationException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OO_Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OO_Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OO_Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OO_Restaurant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
                
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OO_Restaurant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnExit;
    private javax.swing.JButton jBtnReceipt;
    private javax.swing.JButton jBtnReset;
    private javax.swing.JButton jBtnTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTBurger;
    private javax.swing.JTextField jTChocMilkshake;
    private javax.swing.JTextField jTColdCoffee;
    private javax.swing.JTextField jTIceTea;
    private javax.swing.JTextField jTKitKatShake;
    private javax.swing.JTextField jTMomos;
    private javax.swing.JTextField jTNoodles;
    private javax.swing.JTextField jTOreoShake;
    private javax.swing.JTextField jTPIzza;
    private javax.swing.JTextField jTSandwich;
    private javax.swing.JTextField jTxtDrinksCost;
    private javax.swing.JTextField jTxtMealsCost;
    private javax.swing.JTextArea jTxtReceipt;
    private javax.swing.JTextField jTxtSubTotal;
    private javax.swing.JTextField jTxtTax;
    private javax.swing.JTextField jTxtTotalAmount;
    private javax.swing.JTextField jTxtTotalCost;
    private javax.swing.JLabel jbChocolateMilkshake;
    private javax.swing.JLabel jbColdCoffee;
    private javax.swing.JLabel jbCostOfDrinks;
    private javax.swing.JLabel jbCostOfMeal;
    private javax.swing.JLabel jbFarmHousePizzza;
    private javax.swing.JLabel jbHakkaNoodles;
    private javax.swing.JLabel jbIceTea;
    private javax.swing.JLabel jbKitKatShake;
    private javax.swing.JLabel jbOreoShake;
    private javax.swing.JLabel jbSpecialBurger;
    private javax.swing.JLabel jbSubTotal;
    private javax.swing.JLabel jbTandooriMomos;
    private javax.swing.JLabel jbTax;
    private javax.swing.JLabel jbTax3;
    private javax.swing.JLabel jbTax4;
    private javax.swing.JLabel jbTotal;
    private javax.swing.JLabel jbTotalCostOfFood;
    private javax.swing.JLabel jbVegCheeseSandwich;
    // End of variables declaration//GEN-END:variables
}
